baseURL = "http://www.kulturhofkeller.at/"
languageCode = "de-at"
theme = "bulma-base"
publishDir = "kulturhof-villach.github.io"
DefaultContentLanguage = "de"

[params]
name = "Verein kult:villach"
address = "Lederergasse 17, 9500 Villach"
email = "office@kulturhofkeller.at"
phone = "+43 699 15088177"
[params.social]
[params.social.instagram]
name = "instagram"
link = "https://www.instagram.com/kulturhofkeller/"
icon = "fab fa-instagram fa-lg"
[params.social.facebook]
  name = "facebook"
  link = "http://www.facebook.com/kulturhofkeller"
  icon = "fab fa-facebook-square fa-lg"
[params.social.youtube]
  name = "youtube"
  link = "https://www.youtube.com/channel/UCgnVBE8INeLEh50VaZlSZZg"
  icon = "fab fa-youtube fa-lg"


[languages]
  [languages.en]
    languageName = "English"
    title = "kulturhof:keller"
    description = "Cultural Centre | Villach"
    about = "Die Räumlichkeiten im ehemaligen Cling Keller, die sich einerseits in einem für Villach historisch bedeutenden Haus liegen und andererseits auch schon lange als Veranstaltungslocation dienten, bieten in verschiedenen Räumen und auf verschiedenen Ebenen Platz für Veranstaltungen aller Art. Es gibt einen größeren Veranstaltungsraum, der Platz für mindestens 300 BesucherInnen (ca. 100 Sitzplätze) bietet und einen kleineren Raum, der für kleinere Veranstaltungen, wie zum Beispiel Lesungen, ausreichend Platz bietet. Somit ist garantiert, dass je nach Veranstaltungsgröße auch ein geeigneter Raum zur Verfügung gestellt werden kann. Dazwischen gibt es noch Aufenthaltsräume, Nischen und einen Durchgang, der ebenfalls bei Veranstaltungen für diejenigen zur Verfügung steht, die sich abseits eines Konzerts, beispielsweise, unterhalten wollen."
    weight = 1
    announcement = "Test Announcement"


    [language.en.newsletter]
      title = "Subscribe"


    [[languages.en.menu.main]]
    name = "Events"
    pre = "fa fa-calendar-alt"
    url = "events/"
    weight = 4

    [[languages.en.menu.main]]
    name = "Blog"
    pre = "far fa-newspaper"
    url = "blog/"
    weight = 5


  [languages.de]
    languageName = "Deutsch"
    title = "kulturhof:keller"
    description = "Kulturzentrum | Villach"
    about = "Die Räumlichkeiten im ehemaligen Cling Keller, die sich einerseits in einem für Villach historisch bedeutenden Haus liegen und andererseits auch schon lange als Veranstaltungslocation dienten, bieten in verschiedenen Räumen und auf verschiedenen Ebenen Platz für Veranstaltungen aller Art. Es gibt einen größeren Veranstaltungsraum, der Platz für mindestens 300 BesucherInnen (ca. 100 Sitzplätze) bietet und einen kleineren Raum, der für kleinere Veranstaltungen, wie zum Beispiel Lesungen, ausreichend Platz bietet. Somit ist garantiert, dass je nach Veranstaltungsgröße auch ein geeigneter Raum zur Verfügung gestellt werden kann. Dazwischen gibt es noch Aufenthaltsräume, Nischen und einen Durchgang, der ebenfalls bei Veranstaltungen für diejenigen zur Verfügung steht, die sich abseits eines Konzerts, beispielsweise, unterhalten wollen."
    weight = 2
    announcement = "Test Announcement"



    [[languages.de.menu.main]]
    name = "Veranstaltungen"
    pre = "fas fa-theater-masks"
    url = "events/"
    weight = 4

    [[languages.de.menu.main]]
    name = "Blog"
    pre = "far fa-newspaper"
    url = "blog/"
    weight = 5


[params.logo]
    mobile = "/logo_white.svg"
    standard  = "/logo_white.svg"
    notext = "/logo_white.svg"
    heroImg = "/img/mood.jpg"
