baseURL = "https://www.kulturhofkeller.at/"
languageCode = "de-at"
theme = "bulma-base"
publishDir = "kulturhof-villach.github.io"
DefaultContentLanguage = "de"

[params]
name = "Verein kult:villach"
address = "Lederergasse 15, 9500 Villach"
email = "office@kulturhofkeller.at"
phone = "+43 699 15088177"
[params.social]
[params.social.instagram]
name = "instagram"
link = "https://www.instagram.com/kulturhofkeller/"
icon = "fab fa-instagram fa-lg"
[params.social.facebook]
  name = "facebook"
  link = "http://www.facebook.com/kulturhofkeller"
  icon = "fab fa-facebook-square fa-lg"
[params.social.youtube]
  name = "youtube"
  link = "https://www.youtube.com/channel/UCgnVBE8INeLEh50VaZlSZZg"
  icon = "fab fa-youtube fa-lg"


[languages]
  [languages.en]
    languageName = "English"
    title = "kulturhof:keller"
    description = "Cultural Centre | Villach"
    about = "Das Kulturzentrum Kulturhofkeller bringt seit 2011 verschiedenste Veranstaltungen und KünstlerInnen in die Villacher Innenstadt. Neben Eigenveranstaltungen mit Konzerten (inter)nationaler KünstlerInnen (Tiger Lillies, Peterlicht Nino aus Wien, Voodoo Jürgens,...) gibt es auch Theater, Kabarett, Lesungen, Workshops, Vorträge in Kooperation mit diversen Vereinen. Damit bietet der Kulturhofkeller ein sehr breites Spektrum an Kulturprogramm, mit dem Anspruch auch all dem eine Bühne zu bieten, das sonst nirgends seinen Platz findet. Für die Bar-Betreuung bei den Veranstaltungen sorgt der Soundclub LOCO, der am Wochenende ab 22 Uhr auch verschiedenste Partys mit DJs veranstaltet und das Programm des Kulturhofkeller mit seiner Clubschiene ergänzt. Im Innenhof befindet sich das Kaffee Kleinfein, wo man tagsüber gemütlich eine Pause einlegen kann.Der Kulturhofkeller kann für Veranstaltungen gemietet werden. Schreiben Sie dafür ein Email an [office@kulturhofkeller.at](mailto:office@kulturhofkeller.at)"
    weight = 1
    announcement = "Test Announcement"


    [language.en.newsletter]
      title = "Subscribe"


    [[languages.en.menu.main]]
    name = "Events"
    pre = "fa fa-calendar-alt"
    url = "events/"
    weight = 4

    [[languages.en.menu.main]]
    name = "Blog"
    pre = "far fa-newspaper"
    url = "blog/"
    weight = 5


  [languages.de]
    languageName = "Deutsch"
    title = "kulturhof:keller"
    description = "Kulturzentrum | Villach"
    about = "Das Kulturzentrum Kulturhofkeller bringt seit 2011 verschiedenste Veranstaltungen und KünstlerInnen in die Villacher Innenstadt. Neben Eigenveranstaltungen mit Konzerten (inter)nationaler KünstlerInnen (Tiger Lillies, Peterlicht Nino aus Wien, Voodoo Jürgens,...) gibt es auch Theater, Kabarett, Lesungen, Workshops, Vorträge in Kooperation mit diversen Vereinen. Damit bietet der Kulturhofkeller ein sehr breites Spektrum an Kulturprogramm, mit dem Anspruch auch all dem eine Bühne zu bieten, das sonst nirgends seinen Platz findet. Für die Bar-Betreuung bei den Veranstaltungen sorgt der Soundclub LOCO, der am Wochenende ab 22 Uhr auch verschiedenste Partys mit DJs veranstaltet und das Programm des Kulturhofkeller mit seiner Clubschiene ergänzt. Im Innenhof befindet sich das Kaffee Kleinfein, wo man tagsüber gemütlich eine Pause einlegen kann.Der Kulturhofkeller kann für Veranstaltungen gemietet werden. Schreiben Sie dafür ein Email an [office@kulturhofkeller.at](mailto:office@kulturhofkeller.at)"
    weight = 2
    announcement = "Test Announcement"



    [[languages.de.menu.main]]
    name = "Veranstaltungen"
    pre = "fas fa-theater-masks"
    url = "events/"
    weight = 4

    [[languages.de.menu.main]]
    name = "Blog"
    pre = "far fa-newspaper"
    url = "blog/"
    weight = 5


[params.logo]
    mobile = "/logo_white.svg"
    standard  = "/logo_white.svg"
    notext = "/logo_white.svg"
    heroImg = "/img/co_wiecooperation2.jpg"
    stadt = "img/logos/stadt.jpg"
    land = "img/logos/land.png"
    bund = "img/logos/bund.jpg"
